'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace WarenverwaltungServiceReference
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Ware", [Namespace]:="http://schemas.datacontract.org/2004/07/Optify"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Ware
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BeschreibungField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BezeichnungField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IDField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PreisField As Double
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Beschreibung() As String
            Get
                Return Me.BeschreibungField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BeschreibungField, value) <> true) Then
                    Me.BeschreibungField = value
                    Me.RaisePropertyChanged("Beschreibung")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Bezeichnung() As String
            Get
                Return Me.BezeichnungField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BezeichnungField, value) <> true) Then
                    Me.BezeichnungField = value
                    Me.RaisePropertyChanged("Bezeichnung")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ID() As Integer
            Get
                Return Me.IDField
            End Get
            Set
                If (Me.IDField.Equals(value) <> true) Then
                    Me.IDField = value
                    Me.RaisePropertyChanged("ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Preis() As Double
            Get
                Return Me.PreisField
            End Get
            Set
                If (Me.PreisField.Equals(value) <> true) Then
                    Me.PreisField = value
                    Me.RaisePropertyChanged("Preis")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WarenverwaltungServiceReference.IWarenverwaltungService")>  _
    Public Interface IWarenverwaltungService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWarenverwaltungService/alleWarenLaden", ReplyAction:="http://tempuri.org/IWarenverwaltungService/alleWarenLadenResponse")>  _
        Function alleWarenLaden() As System.Collections.Generic.List(Of WarenverwaltungServiceReference.Ware)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWarenverwaltungService/alleWarenLaden", ReplyAction:="http://tempuri.org/IWarenverwaltungService/alleWarenLadenResponse")>  _
        Function alleWarenLadenAsync() As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of WarenverwaltungServiceReference.Ware))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWarenverwaltungService/wareOeffnen", ReplyAction:="http://tempuri.org/IWarenverwaltungService/wareOeffnenResponse")>  _
        Function wareOeffnen(ByVal pIntId As Integer) As WarenverwaltungServiceReference.Ware
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWarenverwaltungService/wareOeffnen", ReplyAction:="http://tempuri.org/IWarenverwaltungService/wareOeffnenResponse")>  _
        Function wareOeffnenAsync(ByVal pIntId As Integer) As System.Threading.Tasks.Task(Of WarenverwaltungServiceReference.Ware)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWarenverwaltungService/wareLoeschen", ReplyAction:="http://tempuri.org/IWarenverwaltungService/wareLoeschenResponse")>  _
        Sub wareLoeschen(ByVal pintId As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWarenverwaltungService/wareLoeschen", ReplyAction:="http://tempuri.org/IWarenverwaltungService/wareLoeschenResponse")>  _
        Function wareLoeschenAsync(ByVal pintId As Integer) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWarenverwaltungService/wareSpeichern", ReplyAction:="http://tempuri.org/IWarenverwaltungService/wareSpeichernResponse")>  _
        Sub wareSpeichern(ByVal pWare As WarenverwaltungServiceReference.Ware)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWarenverwaltungService/wareSpeichern", ReplyAction:="http://tempuri.org/IWarenverwaltungService/wareSpeichernResponse")>  _
        Function wareSpeichernAsync(ByVal pWare As WarenverwaltungServiceReference.Ware) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWarenverwaltungService/wareHinzufuegen", ReplyAction:="http://tempuri.org/IWarenverwaltungService/wareHinzufuegenResponse")>  _
        Function wareHinzufuegen(ByVal pWare As WarenverwaltungServiceReference.Ware) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWarenverwaltungService/wareHinzufuegen", ReplyAction:="http://tempuri.org/IWarenverwaltungService/wareHinzufuegenResponse")>  _
        Function wareHinzufuegenAsync(ByVal pWare As WarenverwaltungServiceReference.Ware) As System.Threading.Tasks.Task(Of Integer)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IWarenverwaltungServiceChannel
        Inherits WarenverwaltungServiceReference.IWarenverwaltungService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WarenverwaltungServiceClient
        Inherits System.ServiceModel.ClientBase(Of WarenverwaltungServiceReference.IWarenverwaltungService)
        Implements WarenverwaltungServiceReference.IWarenverwaltungService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function alleWarenLaden() As System.Collections.Generic.List(Of WarenverwaltungServiceReference.Ware) Implements WarenverwaltungServiceReference.IWarenverwaltungService.alleWarenLaden
            Return MyBase.Channel.alleWarenLaden
        End Function
        
        Public Function alleWarenLadenAsync() As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of WarenverwaltungServiceReference.Ware)) Implements WarenverwaltungServiceReference.IWarenverwaltungService.alleWarenLadenAsync
            Return MyBase.Channel.alleWarenLadenAsync
        End Function
        
        Public Function wareOeffnen(ByVal pIntId As Integer) As WarenverwaltungServiceReference.Ware Implements WarenverwaltungServiceReference.IWarenverwaltungService.wareOeffnen
            Return MyBase.Channel.wareOeffnen(pIntId)
        End Function
        
        Public Function wareOeffnenAsync(ByVal pIntId As Integer) As System.Threading.Tasks.Task(Of WarenverwaltungServiceReference.Ware) Implements WarenverwaltungServiceReference.IWarenverwaltungService.wareOeffnenAsync
            Return MyBase.Channel.wareOeffnenAsync(pIntId)
        End Function
        
        Public Sub wareLoeschen(ByVal pintId As Integer) Implements WarenverwaltungServiceReference.IWarenverwaltungService.wareLoeschen
            MyBase.Channel.wareLoeschen(pintId)
        End Sub
        
        Public Function wareLoeschenAsync(ByVal pintId As Integer) As System.Threading.Tasks.Task Implements WarenverwaltungServiceReference.IWarenverwaltungService.wareLoeschenAsync
            Return MyBase.Channel.wareLoeschenAsync(pintId)
        End Function
        
        Public Sub wareSpeichern(ByVal pWare As WarenverwaltungServiceReference.Ware) Implements WarenverwaltungServiceReference.IWarenverwaltungService.wareSpeichern
            MyBase.Channel.wareSpeichern(pWare)
        End Sub
        
        Public Function wareSpeichernAsync(ByVal pWare As WarenverwaltungServiceReference.Ware) As System.Threading.Tasks.Task Implements WarenverwaltungServiceReference.IWarenverwaltungService.wareSpeichernAsync
            Return MyBase.Channel.wareSpeichernAsync(pWare)
        End Function
        
        Public Function wareHinzufuegen(ByVal pWare As WarenverwaltungServiceReference.Ware) As Integer Implements WarenverwaltungServiceReference.IWarenverwaltungService.wareHinzufuegen
            Return MyBase.Channel.wareHinzufuegen(pWare)
        End Function
        
        Public Function wareHinzufuegenAsync(ByVal pWare As WarenverwaltungServiceReference.Ware) As System.Threading.Tasks.Task(Of Integer) Implements WarenverwaltungServiceReference.IWarenverwaltungService.wareHinzufuegenAsync
            Return MyBase.Channel.wareHinzufuegenAsync(pWare)
        End Function
    End Class
End Namespace
