'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace BenutzerverwaltungServiceReference
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="BenutzerverwaltungServiceReference.IBenutzerverwaltung")>  _
    Public Interface IBenutzerverwaltung
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IBenutzerverwaltung/DoWork", ReplyAction:="http://tempuri.org/IBenutzerverwaltung/DoWorkResponse")>  _
        Sub DoWork()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IBenutzerverwaltung/DoWork", ReplyAction:="http://tempuri.org/IBenutzerverwaltung/DoWorkResponse")>  _
        Function DoWorkAsync() As System.Threading.Tasks.Task
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IBenutzerverwaltungChannel
        Inherits BenutzerverwaltungServiceReference.IBenutzerverwaltung, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class BenutzerverwaltungClient
        Inherits System.ServiceModel.ClientBase(Of BenutzerverwaltungServiceReference.IBenutzerverwaltung)
        Implements BenutzerverwaltungServiceReference.IBenutzerverwaltung
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Sub DoWork() Implements BenutzerverwaltungServiceReference.IBenutzerverwaltung.DoWork
            MyBase.Channel.DoWork
        End Sub
        
        Public Function DoWorkAsync() As System.Threading.Tasks.Task Implements BenutzerverwaltungServiceReference.IBenutzerverwaltung.DoWorkAsync
            Return MyBase.Channel.DoWorkAsync
        End Function
    End Class
End Namespace
