'------------------------------------------------------------------------------
' <auto-generated>
'     Der Code wurde von einer Vorlage generiert.
'
'     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
'     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BestellungEntity
    Public Property bestIdPk As Integer
    Public Property bestDatum As Nullable(Of Date)
    Public Property bestWaren As Nullable(Of Integer)
    Public Property bestPreis As Nullable(Of Double)
    Public Property bestStatus As String

    Public Overridable Property tblBenutzer As ICollection(Of BenutzerEntity) = New HashSet(Of BenutzerEntity)
    Public Overridable Property tblWaren As WareEntity
    Public Overridable Property tblLieferungen As ICollection(Of LieferungEntity) = New HashSet(Of LieferungEntity)

End Class
