'------------------------------------------------------------------------------
' <auto-generated>
'     Der Code wurde von einer Vorlage generiert.
'
'     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
'     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BestellpositionenEntity
    Public Property bestPoIdPk As Integer
    Public Property bestPoWIdFk As Integer
    Public Property bestPoAnzahl As Integer

    Public Overridable Property tblWaren As WarenEntity
    Public Overridable Property tblBestellungen As ICollection(Of BestellungenEntity) = New HashSet(Of BestellungenEntity)

End Class
