'------------------------------------------------------------------------------
' <auto-generated>
'     Der Code wurde von einer Vorlage generiert.
'
'     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
'     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BestellungenEntity
    Public Property bestIdPk As Integer
    Public Property bestDatum As Nullable(Of Date)
    Public Property bestPreis As Nullable(Of Double)
    Public Property bestStatus As String
    Public Property bestPoIdFk As Integer

    Public Overridable Property tblBestellpositionen As BestellpositionenEntity
    Public Overridable Property tblKunde As ICollection(Of KundenEntity) = New HashSet(Of KundenEntity)
    Public Overridable Property tblLieferungen As ICollection(Of LieferungenEntity) = New HashSet(Of LieferungenEntity)

End Class
