'------------------------------------------------------------------------------
' <auto-generated>
'     Der Code wurde von einer Vorlage generiert.
'
'     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
'     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LieferungEntity
    Public Property lieferIdPk As Integer
    Public Property datAnfang As Nullable(Of Date)
    Public Property datEnde As Nullable(Of Date)
    Public Property bestIdFk As Nullable(Of Integer)
    Public Property benIdFk As Nullable(Of Integer)

    Public Overridable Property tblBenutzer As BenutzerEntity
    Public Overridable Property tblBestellungen As BestellungEntity

End Class
