'------------------------------------------------------------------------------
' <auto-generated>
'     Der Code wurde von einer Vorlage generiert.
'
'     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
'     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LieferungenEntity
    Public Property lieferIdPk As Integer
    Public Property datAnfang As Date
    Public Property datEnde As Date
    Public Property bestIdFk As Integer
    Public Property liefIdFk As Integer

    Public Overridable Property tblBestellungen As BestellungenEntity
    Public Overridable Property tblLieferanten As LieferantenEntity

End Class
