'------------------------------------------------------------------------------
' <auto-generated>
'     Der Code wurde von einer Vorlage generiert.
'
'     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
'     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class OptifyEntities1
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=OptifyEntities1")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property tblBestellpositionen() As DbSet(Of BestellpositionenEntity)
    Public Overridable Property tblBestellungen() As DbSet(Of BestellungenEntity)
    Public Overridable Property tblKunde() As DbSet(Of KundenEntity)
    Public Overridable Property tblLieferanten() As DbSet(Of LieferantenEntity)
    Public Overridable Property tblLieferungen() As DbSet(Of LieferungenEntity)
    Public Overridable Property tblMitarbeiter() As DbSet(Of MitarbeiterEntity)
    Public Overridable Property tblWaren() As DbSet(Of WarenEntity)

End Class
