'------------------------------------------------------------------------------
' <auto-generated>
'     Der Code wurde von einer Vorlage generiert.
'
'     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
'     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class WareEntity
    Public Property wIdPk As Integer
    Public Property wTyp As String
    Public Property wPreis As Nullable(Of Double)

    Public Overridable Property tblBestellungen As ICollection(Of BestellungEntity) = New HashSet(Of BestellungEntity)

End Class
