'------------------------------------------------------------------------------
' <auto-generated>
'     Der Code wurde von einer Vorlage generiert.
'
'     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
'     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class WarenEntity
    Public Property wIdPk As Integer
    Public Property wBezeichnung As String
    Public Property wPreis As Nullable(Of Double)
    Public Property wBeschreibung As String
    Public Property wBild As Byte()

    Public Overridable Property tblBestellpositionen As ICollection(Of BestellpositionenEntity) = New HashSet(Of BestellpositionenEntity)

End Class
