'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace BestellungServiceReference
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Bestellung", [Namespace]:="http://schemas.datacontract.org/2004/07/Optify"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Bestellung
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BestellungIDField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DatumBestellungField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PreisField As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StatusField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private WarenField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BestellungID() As Integer
            Get
                Return Me.BestellungIDField
            End Get
            Set
                If (Me.BestellungIDField.Equals(value) <> true) Then
                    Me.BestellungIDField = value
                    Me.RaisePropertyChanged("BestellungID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DatumBestellung() As Date
            Get
                Return Me.DatumBestellungField
            End Get
            Set
                If (Me.DatumBestellungField.Equals(value) <> true) Then
                    Me.DatumBestellungField = value
                    Me.RaisePropertyChanged("DatumBestellung")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Preis() As Decimal
            Get
                Return Me.PreisField
            End Get
            Set
                If (Me.PreisField.Equals(value) <> true) Then
                    Me.PreisField = value
                    Me.RaisePropertyChanged("Preis")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Status() As String
            Get
                Return Me.StatusField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StatusField, value) <> true) Then
                    Me.StatusField = value
                    Me.RaisePropertyChanged("Status")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Waren() As Integer
            Get
                Return Me.WarenField
            End Get
            Set
                If (Me.WarenField.Equals(value) <> true) Then
                    Me.WarenField = value
                    Me.RaisePropertyChanged("Waren")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="BestellungServiceReference.IBestellungverwaltung")>  _
    Public Interface IBestellungverwaltung
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IBestellungverwaltung/gibBestellungen", ReplyAction:="http://tempuri.org/IBestellungverwaltung/gibBestellungenResponse")>  _
        Function gibBestellungen() As System.Collections.Generic.List(Of BestellungServiceReference.Bestellung)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IBestellungverwaltung/gibBestellungen", ReplyAction:="http://tempuri.org/IBestellungverwaltung/gibBestellungenResponse")>  _
        Function gibBestellungenAsync() As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of BestellungServiceReference.Bestellung))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IBestellungverwaltung/BestellungOeffnen", ReplyAction:="http://tempuri.org/IBestellungverwaltung/BestellungOeffnenResponse")>  _
        Function BestellungOeffnen(ByVal pintBestID As Integer) As BestellungServiceReference.Bestellung
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IBestellungverwaltung/BestellungOeffnen", ReplyAction:="http://tempuri.org/IBestellungverwaltung/BestellungOeffnenResponse")>  _
        Function BestellungOeffnenAsync(ByVal pintBestID As Integer) As System.Threading.Tasks.Task(Of BestellungServiceReference.Bestellung)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IBestellungverwaltung/BestellungBearbeiten", ReplyAction:="http://tempuri.org/IBestellungverwaltung/BestellungBearbeitenResponse")>  _
        Sub BestellungBearbeiten(ByVal pBestellung As BestellungServiceReference.Bestellung)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IBestellungverwaltung/BestellungBearbeiten", ReplyAction:="http://tempuri.org/IBestellungverwaltung/BestellungBearbeitenResponse")>  _
        Function BestellungBearbeitenAsync(ByVal pBestellung As BestellungServiceReference.Bestellung) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IBestellungverwaltung/BestellungStornieren", ReplyAction:="http://tempuri.org/IBestellungverwaltung/BestellungStornierenResponse")>  _
        Sub BestellungStornieren(ByVal pintBestID As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IBestellungverwaltung/BestellungStornieren", ReplyAction:="http://tempuri.org/IBestellungverwaltung/BestellungStornierenResponse")>  _
        Function BestellungStornierenAsync(ByVal pintBestID As Integer) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IBestellungverwaltung/Bestellungspeichern", ReplyAction:="http://tempuri.org/IBestellungverwaltung/BestellungspeichernResponse")>  _
        Sub Bestellungspeichern(ByVal pBestellung As BestellungServiceReference.Bestellung)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IBestellungverwaltung/Bestellungspeichern", ReplyAction:="http://tempuri.org/IBestellungverwaltung/BestellungspeichernResponse")>  _
        Function BestellungspeichernAsync(ByVal pBestellung As BestellungServiceReference.Bestellung) As System.Threading.Tasks.Task
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IBestellungverwaltungChannel
        Inherits BestellungServiceReference.IBestellungverwaltung, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class BestellungverwaltungClient
        Inherits System.ServiceModel.ClientBase(Of BestellungServiceReference.IBestellungverwaltung)
        Implements BestellungServiceReference.IBestellungverwaltung
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function gibBestellungen() As System.Collections.Generic.List(Of BestellungServiceReference.Bestellung) Implements BestellungServiceReference.IBestellungverwaltung.gibBestellungen
            Return MyBase.Channel.gibBestellungen
        End Function
        
        Public Function gibBestellungenAsync() As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of BestellungServiceReference.Bestellung)) Implements BestellungServiceReference.IBestellungverwaltung.gibBestellungenAsync
            Return MyBase.Channel.gibBestellungenAsync
        End Function
        
        Public Function BestellungOeffnen(ByVal pintBestID As Integer) As BestellungServiceReference.Bestellung Implements BestellungServiceReference.IBestellungverwaltung.BestellungOeffnen
            Return MyBase.Channel.BestellungOeffnen(pintBestID)
        End Function
        
        Public Function BestellungOeffnenAsync(ByVal pintBestID As Integer) As System.Threading.Tasks.Task(Of BestellungServiceReference.Bestellung) Implements BestellungServiceReference.IBestellungverwaltung.BestellungOeffnenAsync
            Return MyBase.Channel.BestellungOeffnenAsync(pintBestID)
        End Function
        
        Public Sub BestellungBearbeiten(ByVal pBestellung As BestellungServiceReference.Bestellung) Implements BestellungServiceReference.IBestellungverwaltung.BestellungBearbeiten
            MyBase.Channel.BestellungBearbeiten(pBestellung)
        End Sub
        
        Public Function BestellungBearbeitenAsync(ByVal pBestellung As BestellungServiceReference.Bestellung) As System.Threading.Tasks.Task Implements BestellungServiceReference.IBestellungverwaltung.BestellungBearbeitenAsync
            Return MyBase.Channel.BestellungBearbeitenAsync(pBestellung)
        End Function
        
        Public Sub BestellungStornieren(ByVal pintBestID As Integer) Implements BestellungServiceReference.IBestellungverwaltung.BestellungStornieren
            MyBase.Channel.BestellungStornieren(pintBestID)
        End Sub
        
        Public Function BestellungStornierenAsync(ByVal pintBestID As Integer) As System.Threading.Tasks.Task Implements BestellungServiceReference.IBestellungverwaltung.BestellungStornierenAsync
            Return MyBase.Channel.BestellungStornierenAsync(pintBestID)
        End Function
        
        Public Sub Bestellungspeichern(ByVal pBestellung As BestellungServiceReference.Bestellung) Implements BestellungServiceReference.IBestellungverwaltung.Bestellungspeichern
            MyBase.Channel.Bestellungspeichern(pBestellung)
        End Sub
        
        Public Function BestellungspeichernAsync(ByVal pBestellung As BestellungServiceReference.Bestellung) As System.Threading.Tasks.Task Implements BestellungServiceReference.IBestellungverwaltung.BestellungspeichernAsync
            Return MyBase.Channel.BestellungspeichernAsync(pBestellung)
        End Function
    End Class
End Namespace
