'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace AnmeldungsfunktionServiceReference
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Benutzer", [Namespace]:="http://schemas.datacontract.org/2004/07/Optify"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(AnmeldungsfunktionServiceReference.Kunde)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(AnmeldungsfunktionServiceReference.Lieferant)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(AnmeldungsfunktionServiceReference.Mitarbeiter))>  _
    Partial Public Class Benutzer
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BenutzerIDField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BenutzernameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PasswortField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TypField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private VornameField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BenutzerID() As Integer
            Get
                Return Me.BenutzerIDField
            End Get
            Set
                If (Me.BenutzerIDField.Equals(value) <> true) Then
                    Me.BenutzerIDField = value
                    Me.RaisePropertyChanged("BenutzerID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Benutzername() As String
            Get
                Return Me.BenutzernameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BenutzernameField, value) <> true) Then
                    Me.BenutzernameField = value
                    Me.RaisePropertyChanged("Benutzername")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Name() As String
            Get
                Return Me.NameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NameField, value) <> true) Then
                    Me.NameField = value
                    Me.RaisePropertyChanged("Name")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Passwort() As String
            Get
                Return Me.PasswortField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PasswortField, value) <> true) Then
                    Me.PasswortField = value
                    Me.RaisePropertyChanged("Passwort")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Typ() As String
            Get
                Return Me.TypField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TypField, value) <> true) Then
                    Me.TypField = value
                    Me.RaisePropertyChanged("Typ")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Vorname() As String
            Get
                Return Me.VornameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.VornameField, value) <> true) Then
                    Me.VornameField = value
                    Me.RaisePropertyChanged("Vorname")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Kunde", [Namespace]:="http://schemas.datacontract.org/2004/07/Optify"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Kunde
        Inherits AnmeldungsfunktionServiceReference.Benutzer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AdresseField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FirmennameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SteuerIDField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Adresse() As String
            Get
                Return Me.AdresseField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AdresseField, value) <> true) Then
                    Me.AdresseField = value
                    Me.RaisePropertyChanged("Adresse")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Firmenname() As String
            Get
                Return Me.FirmennameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FirmennameField, value) <> true) Then
                    Me.FirmennameField = value
                    Me.RaisePropertyChanged("Firmenname")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SteuerID() As String
            Get
                Return Me.SteuerIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SteuerIDField, value) <> true) Then
                    Me.SteuerIDField = value
                    Me.RaisePropertyChanged("SteuerID")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Lieferant", [Namespace]:="http://schemas.datacontract.org/2004/07/Optify"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Lieferant
        Inherits AnmeldungsfunktionServiceReference.Benutzer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AdresseField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FirmennameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SteuerIDField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Adresse() As String
            Get
                Return Me.AdresseField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AdresseField, value) <> true) Then
                    Me.AdresseField = value
                    Me.RaisePropertyChanged("Adresse")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Firmenname() As String
            Get
                Return Me.FirmennameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FirmennameField, value) <> true) Then
                    Me.FirmennameField = value
                    Me.RaisePropertyChanged("Firmenname")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SteuerID() As String
            Get
                Return Me.SteuerIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SteuerIDField, value) <> true) Then
                    Me.SteuerIDField = value
                    Me.RaisePropertyChanged("SteuerID")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Mitarbeiter", [Namespace]:="http://schemas.datacontract.org/2004/07/Optify"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Mitarbeiter
        Inherits AnmeldungsfunktionServiceReference.Benutzer
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="AnmeldungsfunktionServiceReference.IAnmeldungsfunktion")>  _
    Public Interface IAnmeldungsfunktion
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IAnmeldungsfunktion/Einloggen", ReplyAction:="http://tempuri.org/IAnmeldungsfunktion/EinloggenResponse")>  _
        Function Einloggen(ByVal pstrBenutzername As String, ByVal pstrPasswort As String) As AnmeldungsfunktionServiceReference.Benutzer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IAnmeldungsfunktion/Einloggen", ReplyAction:="http://tempuri.org/IAnmeldungsfunktion/EinloggenResponse")>  _
        Function EinloggenAsync(ByVal pstrBenutzername As String, ByVal pstrPasswort As String) As System.Threading.Tasks.Task(Of AnmeldungsfunktionServiceReference.Benutzer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IAnmeldungsfunktion/gibKunde", ReplyAction:="http://tempuri.org/IAnmeldungsfunktion/gibKundeResponse")>  _
        Function gibKunde(ByVal pBen As AnmeldungsfunktionServiceReference.Benutzer) As AnmeldungsfunktionServiceReference.Kunde
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IAnmeldungsfunktion/gibKunde", ReplyAction:="http://tempuri.org/IAnmeldungsfunktion/gibKundeResponse")>  _
        Function gibKundeAsync(ByVal pBen As AnmeldungsfunktionServiceReference.Benutzer) As System.Threading.Tasks.Task(Of AnmeldungsfunktionServiceReference.Kunde)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IAnmeldungsfunktion/gibLieferant", ReplyAction:="http://tempuri.org/IAnmeldungsfunktion/gibLieferantResponse")>  _
        Function gibLieferant(ByVal pBen As AnmeldungsfunktionServiceReference.Benutzer) As AnmeldungsfunktionServiceReference.Lieferant
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IAnmeldungsfunktion/gibLieferant", ReplyAction:="http://tempuri.org/IAnmeldungsfunktion/gibLieferantResponse")>  _
        Function gibLieferantAsync(ByVal pBen As AnmeldungsfunktionServiceReference.Benutzer) As System.Threading.Tasks.Task(Of AnmeldungsfunktionServiceReference.Lieferant)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IAnmeldungsfunktion/gibMitarbeiter", ReplyAction:="http://tempuri.org/IAnmeldungsfunktion/gibMitarbeiterResponse")>  _
        Function gibMitarbeiter(ByVal pBen As AnmeldungsfunktionServiceReference.Benutzer) As AnmeldungsfunktionServiceReference.Mitarbeiter
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IAnmeldungsfunktion/gibMitarbeiter", ReplyAction:="http://tempuri.org/IAnmeldungsfunktion/gibMitarbeiterResponse")>  _
        Function gibMitarbeiterAsync(ByVal pBen As AnmeldungsfunktionServiceReference.Benutzer) As System.Threading.Tasks.Task(Of AnmeldungsfunktionServiceReference.Mitarbeiter)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IAnmeldungsfunktionChannel
        Inherits AnmeldungsfunktionServiceReference.IAnmeldungsfunktion, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class AnmeldungsfunktionClient
        Inherits System.ServiceModel.ClientBase(Of AnmeldungsfunktionServiceReference.IAnmeldungsfunktion)
        Implements AnmeldungsfunktionServiceReference.IAnmeldungsfunktion
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Einloggen(ByVal pstrBenutzername As String, ByVal pstrPasswort As String) As AnmeldungsfunktionServiceReference.Benutzer Implements AnmeldungsfunktionServiceReference.IAnmeldungsfunktion.Einloggen
            Return MyBase.Channel.Einloggen(pstrBenutzername, pstrPasswort)
        End Function
        
        Public Function EinloggenAsync(ByVal pstrBenutzername As String, ByVal pstrPasswort As String) As System.Threading.Tasks.Task(Of AnmeldungsfunktionServiceReference.Benutzer) Implements AnmeldungsfunktionServiceReference.IAnmeldungsfunktion.EinloggenAsync
            Return MyBase.Channel.EinloggenAsync(pstrBenutzername, pstrPasswort)
        End Function
        
        Public Function gibKunde(ByVal pBen As AnmeldungsfunktionServiceReference.Benutzer) As AnmeldungsfunktionServiceReference.Kunde Implements AnmeldungsfunktionServiceReference.IAnmeldungsfunktion.gibKunde
            Return MyBase.Channel.gibKunde(pBen)
        End Function
        
        Public Function gibKundeAsync(ByVal pBen As AnmeldungsfunktionServiceReference.Benutzer) As System.Threading.Tasks.Task(Of AnmeldungsfunktionServiceReference.Kunde) Implements AnmeldungsfunktionServiceReference.IAnmeldungsfunktion.gibKundeAsync
            Return MyBase.Channel.gibKundeAsync(pBen)
        End Function
        
        Public Function gibLieferant(ByVal pBen As AnmeldungsfunktionServiceReference.Benutzer) As AnmeldungsfunktionServiceReference.Lieferant Implements AnmeldungsfunktionServiceReference.IAnmeldungsfunktion.gibLieferant
            Return MyBase.Channel.gibLieferant(pBen)
        End Function
        
        Public Function gibLieferantAsync(ByVal pBen As AnmeldungsfunktionServiceReference.Benutzer) As System.Threading.Tasks.Task(Of AnmeldungsfunktionServiceReference.Lieferant) Implements AnmeldungsfunktionServiceReference.IAnmeldungsfunktion.gibLieferantAsync
            Return MyBase.Channel.gibLieferantAsync(pBen)
        End Function
        
        Public Function gibMitarbeiter(ByVal pBen As AnmeldungsfunktionServiceReference.Benutzer) As AnmeldungsfunktionServiceReference.Mitarbeiter Implements AnmeldungsfunktionServiceReference.IAnmeldungsfunktion.gibMitarbeiter
            Return MyBase.Channel.gibMitarbeiter(pBen)
        End Function
        
        Public Function gibMitarbeiterAsync(ByVal pBen As AnmeldungsfunktionServiceReference.Benutzer) As System.Threading.Tasks.Task(Of AnmeldungsfunktionServiceReference.Mitarbeiter) Implements AnmeldungsfunktionServiceReference.IAnmeldungsfunktion.gibMitarbeiterAsync
            Return MyBase.Channel.gibMitarbeiterAsync(pBen)
        End Function
    End Class
End Namespace
